### Get all items
GET http://localhost:3000/items HTTP/1.1

### Get item by ID
GET http://localhost:3000/items/1 HTTP/1.1

### Add an item
POST http://localhost:3000/items HTTP/1.1
Content-Type: application/json

{
  "name": "Item 4",
  "price": 4.99
}

### Delete item by ID
DELETE http://localhost:3000/items/1 HTTP/1.1

### update item
PUT http://localhost:3000/items/2 HTTP/1.1
Content-Type: application/json

{
  "name": "Item 2 has been updated",
  "price": 2.99
}